### ISSUE TITLE
getwalletinfo - Method not found

### ISSUE THREAD

**Issue by daygle** [LIMXTEC/Megacoin#20]
I am using the latest git (master) and have noticed that the command 'getwalletinfo' shows the error 'Method not found'.

![image](https://user-images.githubusercontent.com/5925233/84620293-ee491980-af1a-11ea-96d4-063b11f63be1.png)

I am running Megacoin on Debian 9 with the latest updates.

Any ideas why this is happening?

**Comment by limxdev** [comment]
No sorry, maybe wrong RPC settings? Works getbalance?

**Comment by joshafest** [comment]
@daygle you can try help rpc , new core have some different rpc
